# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRunSwaggerHealthCheck():
  def setup_method(self, method):
  
    from selenium.webdriver.chrome.options import Options
    options = Options()
    options.add_argument("--headless")
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-gpu')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('disable-infobars')
    options.add_argument("--disable-extensions")
    self.driver = webdriver.Chrome(chrome_options=options)
    #Dynamics wait upto 10 seconds.
    self.driver.implicitly_wait(10)
  
    #self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_runSwaggerHealthCheck(self):
    self.driver.get("https://openhackdevopsapp-poi-staging.azurewebsites.net/api/docs/poi/index.html")
    self.driver.set_window_size(516, 690)
    self.driver.find_element(By.CSS_SELECTOR, "#operations-HealthCheck-ApiHealthcheckPoiGet .opblock-summary-method").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    #actions.move_to_element(element, 0, 0).perform()
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".execute").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".execute")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    #actions.move_to_element(element, 0, 0).perform()
    actions.move_to_element(element).perform()
